/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memoriavirtual;

import java.io.File;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jespi_000
 */
public class VentanaInicio extends javax.swing.JFrame {
    private File ArchivoReferencias;
    private File ArchivoProcesos;

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getRootPane().setDefaultButton(ButtonCargarArchivos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        LabelTitulo = new javax.swing.JLabel();
        LabelSeleccionarArchivoProcesos = new javax.swing.JLabel();
        LabelSeleccionarArchivoRegistros = new javax.swing.JLabel();
        ButtonArchivoProcesos = new javax.swing.JButton();
        ButtonArchivoReferencias = new javax.swing.JButton();
        ButtonCargarArchivos = new javax.swing.JButton();
        LabelArchivoSeleccionadoProcesos = new javax.swing.JLabel();
        LabelArchivoSeleccionadoReferencias = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        Ayuda = new javax.swing.JMenu();
        General = new javax.swing.JMenuItem();
        Creditos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador de Memoria Virtual");

        LabelTitulo.setText("¡Bienvenido al Simulador de Memoria Virtual!");

        LabelSeleccionarArchivoProcesos.setText("A continuación seleccione el archivo de texto de procesos a cargar:");

        LabelSeleccionarArchivoRegistros.setText("A continuación seleccione el archivo de texto de referencias a cargar:");

        ButtonArchivoProcesos.setText("Seleccionar archivo de procesos");
        ButtonArchivoProcesos.setNextFocusableComponent(ButtonArchivoReferencias);
        ButtonArchivoProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonArchivoProcesosActionPerformed(evt);
            }
        });

        ButtonArchivoReferencias.setText("Seleccionar archivo de registros");
        ButtonArchivoReferencias.setNextFocusableComponent(ButtonCargarArchivos);
        ButtonArchivoReferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonArchivoReferenciasActionPerformed(evt);
            }
        });

        ButtonCargarArchivos.setText("Cargar archivos");
        ButtonCargarArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCargarArchivosActionPerformed(evt);
            }
        });

        LabelArchivoSeleccionadoProcesos.setText("Archivo: ");

        LabelArchivoSeleccionadoReferencias.setText("Archivo: ");

        Ayuda.setText("Ayuda");
        Ayuda.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                AyudaMenuSelected(evt);
            }
        });
        Ayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AyudaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AyudaMousePressed(evt);
            }
        });
        Ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudaActionPerformed(evt);
            }
        });

        General.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        General.setText("Ayuda General");
        General.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneralActionPerformed(evt);
            }
        });
        Ayuda.add(General);

        menu.add(Ayuda);

        Creditos.setText("Créditos");
        Creditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreditosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CreditosMousePressed(evt);
            }
        });
        Creditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditosActionPerformed(evt);
            }
        });
        Creditos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CreditosKeyPressed(evt);
            }
        });
        menu.add(Creditos);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelSeleccionarArchivoProcesos)
                            .addComponent(LabelSeleccionarArchivoRegistros)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonArchivoProcesos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LabelArchivoSeleccionadoProcesos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonArchivoReferencias)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LabelArchivoSeleccionadoReferencias)))
                        .addContainerGap(56, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LabelTitulo)
                        .addGap(88, 88, 88))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonCargarArchivos)
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelSeleccionarArchivoProcesos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelArchivoSeleccionadoProcesos)
                    .addComponent(ButtonArchivoProcesos))
                .addGap(29, 29, 29)
                .addComponent(LabelSeleccionarArchivoRegistros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelArchivoSeleccionadoReferencias)
                    .addComponent(ButtonArchivoReferencias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(ButtonCargarArchivos)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneralActionPerformed
        
    }//GEN-LAST:event_GeneralActionPerformed

    private void AyudaMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_AyudaMenuSelected

    }//GEN-LAST:event_AyudaMenuSelected

    private void AyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AyudaMouseClicked

    }//GEN-LAST:event_AyudaMouseClicked

    private void AyudaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AyudaMousePressed

    }//GEN-LAST:event_AyudaMousePressed

    private void AyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudaActionPerformed

    }//GEN-LAST:event_AyudaActionPerformed

    private void CreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreditosMouseClicked
        JOptionPane.showMessageDialog(new JFrame(),"El presente programa fue diseñado y desarrollado para el curso Infraestructura Tecnológica I, I semestre 2015.\n\nLos estudiantes responsables son:\n- Adrián Siles Masís\n- Mauricio Gamboa Cubero\n- Andrés Pacheco Quesada\n- Josué Espinoza Castro","Créditos",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_CreditosMouseClicked

    private void CreditosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreditosMousePressed
        JOptionPane.showMessageDialog(new JFrame(),"El presente programa fue diseñado y desarrollado para el curso Infraestructura Tecnológica I, I semestre 2015.\n\nLos estudiantes responsables son:\n- Adrián Siles Masís\n- Mauricio Gamboa Cubero\n- Andrés Pacheco Quesada\n- Josué Espinoza Castro","Créditos",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_CreditosMousePressed

    private void CreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditosActionPerformed

    }//GEN-LAST:event_CreditosActionPerformed

    private void CreditosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CreditosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreditosKeyPressed

    private void ButtonArchivoReferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonArchivoReferenciasActionPerformed
        File archivo = CargadorArchivos.Cargar();
        if (archivo == null){
            JOptionPane.showMessageDialog(new JFrame(),"Archivo inválido.\nDebe seleccionar un archivo de texto con extensión .txt.","Error al cargar el archivo",JOptionPane.ERROR_MESSAGE);
            LabelArchivoSeleccionadoReferencias.setText("Archivo: ");
        }
        else{
            LabelArchivoSeleccionadoReferencias.setText("Archivo: "+archivo.getName());
            this.ArchivoReferencias = archivo;
        }
    }//GEN-LAST:event_ButtonArchivoReferenciasActionPerformed

    private void ButtonCargarArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCargarArchivosActionPerformed
        //Lista de Strings (1 línea por elemento) de los archivos de texto
        List<String> archivoProcesos;
        List<String> archivoReferencias;
        if (LabelArchivoSeleccionadoProcesos.getText().equals("Archivo: ")){
            JOptionPane.showMessageDialog(new JFrame(),"Debe seleccionar un archivo de texto con extensión .txt para el archivo de procesos.","Ningún archivo cargado",JOptionPane.ERROR_MESSAGE);
        }
        else if (LabelArchivoSeleccionadoReferencias.getText().equals("Archivo: ")){
                JOptionPane.showMessageDialog(new JFrame(),"Debe seleccionar un archivo de texto con extensión .txt para el archivo de referencias.","Ningún archivo cargado",JOptionPane.ERROR_MESSAGE);
        }
        else{ //pasó las validaciones
            archivoProcesos = LeedorArchivos.Leer(ArchivoProcesos.getAbsolutePath());
            archivoReferencias = LeedorArchivos.Leer(ArchivoReferencias.getAbsolutePath());
            
            //Set atributos globales
            Main.lineas_archivos_procesos = archivoProcesos;
            Main.lineas_archivos_referencias = archivoReferencias;
            
            //Mostrar mensaje de éxito y proceder con el sistema
            JOptionPane.showMessageDialog(new JFrame(),"Los archivos se cargaron exitosamente.\nEscoja las configuraciones del sistema de memoria virtual.","Éxito",JOptionPane.PLAIN_MESSAGE);
            this.setVisible(false);
            VentanaConfiguracion ventana_configuracion = new VentanaConfiguracion();
            ventana_configuracion.setVisible(true);
        }
    }//GEN-LAST:event_ButtonCargarArchivosActionPerformed

    private void ButtonArchivoProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonArchivoProcesosActionPerformed
        
        File archivo = CargadorArchivos.Cargar();
        if (archivo == null){
            JOptionPane.showMessageDialog(new JFrame(),"Archivo inválido.\nDebe seleccionar un archivo de texto con extensión .txt.","Error al cargar el archivo",JOptionPane.ERROR_MESSAGE);
            LabelArchivoSeleccionadoProcesos.setText("Archivo: ");
        }
        else{
            LabelArchivoSeleccionadoProcesos.setText("Archivo: "+archivo.getName());
            this.ArchivoProcesos = archivo;
        }
    }//GEN-LAST:event_ButtonArchivoProcesosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ayuda;
    private javax.swing.JButton ButtonArchivoProcesos;
    private javax.swing.JButton ButtonArchivoReferencias;
    private javax.swing.JButton ButtonCargarArchivos;
    private javax.swing.JMenu Creditos;
    private javax.swing.JMenuItem General;
    private javax.swing.JLabel LabelArchivoSeleccionadoProcesos;
    private javax.swing.JLabel LabelArchivoSeleccionadoReferencias;
    private javax.swing.JLabel LabelSeleccionarArchivoProcesos;
    private javax.swing.JLabel LabelSeleccionarArchivoRegistros;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenuBar menu;
    // End of variables declaration//GEN-END:variables
}
